officers:
  - name: "Landon Becker"
    position: "District Commander"
    filter: "Command"
    post: "10076"
    image: "blur.jpg"
  - name: "Allan Yeater"
    position: "District Sr. Vice Commander"
    filter: "Command"
    post: "10076"
    image: "blur.jpg"
  - name: "Robert Dinterman"
    position: "District Jr. Vice Commander"
    filter: "Command"
    post: "6658"
    image: "blur.jpg"
  - name: "Frank Rauschenberg"
    position: "Adjutant"
    filter: "Operations"
    post: "6918"
    image: "blur.jpg"
  - name: "Shelby Rogers"
    position: "District Quartermaster"
    filter: "Operations"
    post: "7472"
    image: "blur.jpg"
  - name: "Dale Owings"
    position: "District Chaplain"
    filter: "Services"
    post: "467"
    image: "blur.jpg"
  - name: "Marty Williams"
    position: "District Surgeon"
    filter: "Services"
    post: "6658"
    image: "blur.jpg"
  - name: "Tony Navickas"
    position: "District Service Officer"
    filter: "Services"
    post: "521"
    image: "blur.jpg"
  - name: "Patrick Pierson"
    position: "District Judge Advocate"
    filter: "Services"
    post: "3285"
    image: "blur.jpg"
  - name: "Tony Navickas"
    position: "District 1st Year Trustee"
    filter: "Trustees"
    post: "521"
    image: "blur.jpg"
  - name: "Sarah Lentz"
    position: "District 2nd Year Trustee"
    filter: "Trustees"
    post: "6918"
    image: "blur.jpg"
  - name: "John Dallatezza"
    position: "District 3rd Year Trustee"
    filter: "Trustees"
    post: "6658"
    image: "blur.jpg"
  - name: "Allan Yeater"
    position: "District Officer of the Day"
    filter: "Operations"
    post: "10076"
    image: "blur.jpg"
  - name: "John Dallatezza"
    position: "District Assistant Quartermaster"
    filter: "Operations"
    post: "6658"
    image: "blur.jpg"
  - name: "Bill Miller"
    position: "District Legislation Officer"
    filter: "Services"
    post: "521"
    image: "blur.jpg"
  - name: "Ralph Murray"
    position: "District Membership"
    filter: "Services"
    post: "521"
    image: "blur.jpg"
  - name: "Charles McConville"
    position: "Past State Commander"
    filter: "Services"
    post: "521"
    image: "blur.jpg"



exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

gems:
  - jekyll-sitemap

# Site settings
title: District 7 VFW Maryland
subtitle: "District 7 VFW Maryland"
url: "https://www.district7vfwmd.org" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
#newsletter: "https://us8.campaign-archive.com/home/?u=bf686e4d27915b21ce1cf42bf&id=d608a5130b"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-141660455-1"

google:
  tag_manager:
    container_id: GTM-MT9RKR2

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
